document.getElementsByClassName('emergency-tasks')[0].style.backgroundColor = '#FFA085ff';
document.getElementsByClassName('no-emergency-tasks')[0].style.backgroundColor = '#F9DC5Eff';
document.querySelectorAll('.emergency-tasks h3')[0].style.backgroundColor = '#A600F3ff';
document.querySelectorAll('.emergency-tasks h3')[1].style.backgroundColor = '#A600F3ff';
document.querySelectorAll('.no-emergency-tasks h3')[0].style.backgroundColor = '#1E2020ff';
document.querySelectorAll('.no-emergency-tasks h3')[1].style.backgroundColor = '#1E2020ff';
document.getElementById('container').style.backgroundColor = '#F3F3F3ff';
document.getElementById('footer-container').style.backgroundColor = '#003230ff';
document.getElementById('header-container').style.backgroundColor = '#00B269ff';